"use client";

import AuthCard from "@/components/auth/auth-card";
import FormError from "@/components/auth/form-error";

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "@/components/ui/input-otp";
import { Loader2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { REGEXP_ONLY_DIGITS } from "input-otp";
import { Button } from "@/components/ui/button";
import { otpSchema, otpSchemaType } from "@/schemas";
import { zodResolver } from "@hookform/resolvers/zod";
import { signInWithTwoFactor } from "@/actions/signin";

const TwoFactorVerification = () => {
  const form = useForm<otpSchemaType>({
    resolver: zodResolver(otpSchema),
    defaultValues: {
      otpCode: "",
    },
  });
  const { isSubmitting, errors } = form.formState;

  const onTwoFactorSubmit = form.handleSubmit(async (otpCode) => {
    const { success, errors } = await signInWithTwoFactor(otpCode);
    if (!success) {
      errors?.forEach(({ name, message }) =>
        form.setError(name as keyof otpSchemaType, { message })
      );
    }
  });

  return (
    <AuthCard
      title="Two-step verification"
      subtitle="To continue, please enter the verification code generated by your authenticator app"
      footer={
        <Button onClick={() => {}} variant="link">
          Back
        </Button>
      }
    >
      <Form {...form}>
        <form onSubmit={onTwoFactorSubmit} className="space-y-6 text-center">
          <FormError message={errors.root?.message} />
          <FormField
            control={form.control}
            name="otpCode"
            render={({ field }) => (
              <FormItem>
                <div className="flex flex-col items-center">
                  <FormControl>
                    <InputOTP
                      autoFocus
                      maxLength={6}
                      pattern={REGEXP_ONLY_DIGITS}
                      disabled={isSubmitting}
                      onComplete={onTwoFactorSubmit}
                      {...field}
                    >
                      {[...Array(6)].map((_, index) => (
                        <InputOTPGroup key={index}>
                          <InputOTPSlot index={index} />
                        </InputOTPGroup>
                      ))}
                    </InputOTP>
                  </FormControl>
                  <FormMessage className="mt-4" />
                </div>
              </FormItem>
            )}
          />

          <Button className="w-full" type="submit" disabled={isSubmitting}>
            {isSubmitting ? <Loader2 className="animate-spin" /> : "Continue"}
          </Button>
        </form>
      </Form>
    </AuthCard>
  );
};
export default TwoFactorVerification;
