name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: acmeinc_db
          POSTGRES_USER: acmeinc_user
          POSTGRES_PASSWORD: tE1_3H8xpiGuDt_zEcIp
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Prisma db push
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          # GITHUB_CLIENT_ID: ${{  secrets.GITHUB_CLIENT_ID  }}
          # GITHUB_CLIENT_SECRET: ${{  secrets.GITHUB_CLIENT_ID  }}
          GOOGLE_CLIENT_ID: ${{  secrets.GOOGLE_CLIENT_ID  }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME }}
          AUTH_TRUST_HOST: http://localhost:3000
          CYPRESS_testing_email: ${{ secrets.TESTING_EMAIL }}
          CYPRESS_testing_password: ${{ secrets.TESTING_PASSWORD }}
          CYPRESS_api_key: ${{ secrets.API_KEY }}
          CYPRESS_testing_namespace: ${{ secrets.TESTING_NAMESPACE }}
